Modificato
MiaOrganizza/RepoOrganizzazione pull request #1
Opened 2019-11-16 22:04 UTC by fenice752002

DImmi se è ok

2019-11-16 22:19 UTC, diegobelliardo commented
OK

2019-11-17 20:38 UTC, diegobelliardo requested changes
Perchè l'hai fatto così?
Andava fatto cosà!

2019-11-17 20:40 UTC, diegobelliardo reviewed
Sei sicuro che vada bene?

2019-11-17 20:41 UTC, fenice752002 commented
> Sei sicuro che vada bene?

Si

2019-11-17 20:43 UTC, merged